[package]
name = "thimble"
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0-or-later OR LGPL-2.1-or-later"
homepage = "https://tapistri.chat"
repository = "https://github.com/Tapistri/thimble"

[dependencies]
falcon-rs = "0.2.5"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
libcrux-ml-kem = "0.0.10"
rand = "0.10.2"
rasn = "0.28.14"
sha2 = "0.11.0"
